"""
mock_llm.py — Simulates OpenCode CLI output without calling any LLM API.

Used when MOCK_LLM=true to enable CI testing without API keys or network access.
Creates a verifiable artifact in the workspace and prints realistic progress output.

REF: JOB-021 T-187
"""

import os
import random
import sys
import time


def run_mock(task_description: str) -> int:
    """
    Simulate OpenCode CLI execution.

    Prints realistic-looking progress output, creates a dummy file in /workspace,
    and returns exit code 0 (success).

    Args:
        task_description: The task description from the command.assign_task payload.

    Returns:
        Exit code 0 on success.
    """
    print("⠋ Analyzing task...", flush=True)
    time.sleep(random.uniform(0.5, 1.0))

    print("⠋ Reading workspace files...", flush=True)
    time.sleep(random.uniform(0.5, 1.0))

    print("⠋ Planning changes...", flush=True)
    time.sleep(random.uniform(0.5, 1.0))

    print("✓ Created src/Example.cs", flush=True)
    time.sleep(random.uniform(0.3, 0.5))

    print("✓ Modified src/Program.cs", flush=True)
    time.sleep(random.uniform(0.3, 0.5))

    # Create a verifiable artifact in the workspace
    workspace = os.environ.get("WORKSPACE_DIR", "/workspace")
    output_path = os.path.join(workspace, "stewie-mock-output.txt")
    try:
        with open(output_path, "w") as f:
            f.write(f"Mock LLM output for task:\n{task_description}\n")
            f.write(f"\nGenerated by stewie-opencode-agent (mock mode)\n")
        print(f"✓ Created {output_path}", flush=True)
    except OSError as e:
        print(f"⚠ Could not write mock output file: {e}", flush=True)

    print("✓ Task complete", flush=True)
    return 0


if __name__ == "__main__":
    description = " ".join(sys.argv[1:]) if len(sys.argv) > 1 else "No task description provided"
    sys.exit(run_mock(description))
